// GENERATED by scripts/write-top-activities.mjs (weekly Windows task «LV Katsotuimmat retket»).
// Do not edit by hand: the next run overwrites it.
//
// GetYourGuide tours that readers across the LaplandVibes sites clicked through to most in the
// 30 days to the date below (go.laplandvibes.com click log, bots excluded), each verified to
// render as itself in GYG's widget. Click counts are deliberately not stored: the log is private.
// The widget ignores this order, so the page never shows a rank.

export const TOP_VIEWED_CHECKED_AT = '2026-09-26';
export const TOP_VIEWED_WINDOW_DAYS = 30;
export const TOP_VIEWED_TOUR_IDS: readonly number[] = [654057, 492901, 693623, 504004, 1120827, 96021];
